#app/config/security.yml
security:
    ecoders:
        FOS\UserBundle\Model\UserInterface: bcrypt
        
        role_hieararchy:
            ROLE_ADMIN: ROLE_USER
            ROLE_SUPER_ADMIN: ROLE_ADMIN
        
        providers:
            fos_userbundle:
                id:fos_user_provider.username
        firewals:
            main:
                pattern:
                form_login:
                    provider:fos_userbundle
                    csrf_provider:security.csrf.token_manager
                logout:     true
                anonymous:  true
                
    access_control:
        - {path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - {path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - {path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - {path: ^/admin/, role: ROLE_ADMIN }